import {useEffect,useState} from 'react';

const API=(import.meta.env.VITE_API_URL||'http://localhost:8081/api').replace(/\/$/,'');
const DEMO_MODE=typeof window!=='undefined'&&window.location.hostname.endsWith('github.io');
const emptyProject={name:'',description:'',status:'PLANNED'};
const emptyTask={title:'',description:'',status:'TODO',priority:'MEDIUM',dueDate:'',projectId:''};
const demoProjects=[
 {id:1,name:'DevVault',description:'Gerenciador de projetos e tarefas desenvolvido com Java e React.',status:'IN_PROGRESS',taskCount:3},
 {id:2,name:'Portfolio',description:'Organização dos projetos e estudos de desenvolvimento.',status:'PLANNED',taskCount:2}
];
const demoTasks=[
 {id:1,title:'Estruturar dashboard',description:'Organizar a visão geral do projeto.',status:'DONE',priority:'HIGH',dueDate:'',projectId:1},
 {id:2,title:'Implementar API REST',description:'Criar endpoints para projetos e tarefas.',status:'IN_PROGRESS',priority:'HIGH',dueDate:'',projectId:1},
 {id:3,title:'Revisar interface',description:'Ajustar detalhes visuais do dashboard.',status:'TODO',priority:'MEDIUM',dueDate:'',projectId:1}
];

function App(){
 const [projects,setProjects]=useState(DEMO_MODE?demoProjects:[]),[tasks,setTasks]=useState(DEMO_MODE?demoTasks:[]),[stats,setStats]=useState(DEMO_MODE?{totalProjects:2,inProgressProjects:1,completedProjects:0,totalTasks:3}:null);
 const [project,setProject]=useState(emptyProject),[task,setTask]=useState(emptyTask);
 const [editing,setEditing]=useState(null),[editingTask,setEditingTask]=useState(null),[error,setError]=useState('');
 const load=async()=>{if(DEMO_MODE){setError('');return}try{const [p,t,d]=await Promise.all([fetch(API+'/projects'),fetch(API+'/tasks'),fetch(API+'/dashboard')]);if(!p.ok||!t.ok||!d.ok)throw new Error('Não foi possível carregar os dados.');setProjects(await p.json());setTasks(await t.json());setStats(await d.json());setError('')}catch(e){setError(e.message)}};
 useEffect(()=>{load()},[]);
 const saveProject=async e=>{e.preventDefault();if(DEMO_MODE){if(editing)setProjects(v=>v.map(p=>p.id===editing?{...p,...project}:p));else setProjects(v=>[...v,{...project,id:Date.now(),taskCount:0}]);setProject(emptyProject);setEditing(null);return}const r=await fetch(editing?API+'/projects/'+editing:API+'/projects',{method:editing?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(project)});if(!r.ok){setError('Não foi possível salvar o projeto.');return}setProject(emptyProject);setEditing(null);load()};
 const removeProject=async id=>{if(!confirm('Excluir este projeto e suas tarefas?'))return;if(DEMO_MODE){setProjects(v=>v.filter(p=>p.id!==id));setTasks(v=>v.filter(t=>t.projectId!==id));return}await fetch(API+'/projects/'+id,{method:'DELETE'});load()};
 const saveTask=async e=>{e.preventDefault();if(DEMO_MODE){const item={...task,id:editingTask||Date.now(),projectId:Number(task.projectId)};if(editingTask)setTasks(v=>v.map(t=>t.id===editingTask?item:t));else setTasks(v=>[...v,item]);setTask(emptyTask);setEditingTask(null);return}const r=await fetch(editingTask?API+'/tasks/'+editingTask:API+'/tasks',{method:editingTask?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...task,projectId:Number(task.projectId)})});if(!r.ok){setError('Não foi possível salvar a tarefa.');return}setTask(emptyTask);setEditingTask(null);load()};
 const removeTask=async id=>{if(DEMO_MODE){setTasks(v=>v.filter(t=>t.id!==id));return}await fetch(API+'/tasks/'+id,{method:'DELETE'});load()};
 const editProject=p=>{setEditing(p.id);setProject({name:p.name,description:p.description||'',status:p.status})};
 const editTask=t=>{setEditingTask(t.id);setTask({title:t.title,description:t.description||'',status:t.status,priority:t.priority,dueDate:t.dueDate||'',projectId:t.projectId})};
 return <main><header><div><span className="eyebrow">DEVELOPER WORKSPACE</span><h1>DevVault</h1><p>Gerencie seus projetos e tarefas em um só lugar.</p></div><button className="ghost" onClick={load}>Atualizar</button></header>
 {DEMO_MODE&&<div className="alert">Modo demonstração — os dados exibidos são locais e não precisam de backend.</div>}
 {error&&<div className="alert">{error}</div>}
 <section className="stats">{[['Projetos',DEMO_MODE?projects.length:stats?.totalProjects??0],['Em andamento',DEMO_MODE?projects.filter(p=>p.status==='IN_PROGRESS').length:stats?.inProgressProjects??0],['Concluídos',DEMO_MODE?projects.filter(p=>p.status==='COMPLETED').length:stats?.completedProjects??0],['Tarefas',DEMO_MODE?tasks.length:stats?.totalTasks??0]].map(([l,v])=><article className="stat" key={l}><span>{l}</span><strong>{v}</strong></article>)}</section>
 <section className="grid"><div className="panel"><div className="panel-title"><h2>{editing?'Editar projeto':'Novo projeto'}</h2></div><form onSubmit={saveProject}><input required placeholder="Nome do projeto" value={project.name} onChange={e=>setProject({...project,name:e.target.value})}/><textarea placeholder="Descrição" value={project.description} onChange={e=>setProject({...project,description:e.target.value})}/><select value={project.status} onChange={e=>setProject({...project,status:e.target.value})}><option value="PLANNED">Planejado</option><option value="IN_PROGRESS">Em andamento</option><option value="COMPLETED">Concluído</option></select><button>{editing?'Salvar alterações':'Criar projeto'}</button>{editing&&<button type="button" className="ghost" onClick={()=>{setEditing(null);setProject(emptyProject)}}>Cancelar</button>}</form></div>
 <div className="panel"><div className="panel-title"><h2>{editingTask?'Editar tarefa':'Nova tarefa'}</h2></div><form onSubmit={saveTask}><input required placeholder="Título da tarefa" value={task.title} onChange={e=>setTask({...task,title:e.target.value})}/><textarea placeholder="Descrição" value={task.description} onChange={e=>setTask({...task,description:e.target.value})}/><div className="row"><select value={task.projectId} required onChange={e=>setTask({...task,projectId:e.target.value})}><option value="">Projeto</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><select value={task.priority} onChange={e=>setTask({...task,priority:e.target.value})}><option value="LOW">Baixa</option><option value="MEDIUM">Média</option><option value="HIGH">Alta</option></select></div><div className="row"><select value={task.status} onChange={e=>setTask({...task,status:e.target.value})}><option value="TODO">A fazer</option><option value="IN_PROGRESS">Em andamento</option><option value="DONE">Concluída</option></select><input type="date" value={task.dueDate} onChange={e=>setTask({...task,dueDate:e.target.value})}/></div><button>{editingTask?'Salvar tarefa':'Criar tarefa'}</button>{editingTask&&<button type="button" className="ghost" onClick={()=>{setEditingTask(null);setTask(emptyTask)}}>Cancelar</button>}</form></div></section>
 <section className="panel"><div className="panel-title"><h2>Projetos</h2><span>{projects.length} cadastrados</span></div>{projects.length===0?<div className="empty">Nenhum projeto cadastrado ainda.</div>:<div className="cards">{projects.map(p=><article className="card" key={p.id}><div className="card-top"><h3>{p.name}</h3><span className="badge">{p.status.replace('_',' ')}</span></div><p>{p.description||'Sem descrição.'}</p><small>{DEMO_MODE?tasks.filter(t=>t.projectId===p.id).length:p.taskCount} tarefa(s)</small><div className="actions"><button className="ghost" onClick={()=>editProject(p)}>Editar</button><button className="danger" onClick={()=>removeProject(p.id)}>Excluir</button></div></article>)}</div>}</section>
 <section className="panel"><div className="panel-title"><h2>Tarefas</h2><span>{tasks.length} cadastradas</span></div>{tasks.length===0?<div className="empty">Nenhuma tarefa cadastrada ainda.</div>:<div className="task-list">{tasks.map(t=><article className="task" key={t.id}><div><strong>{t.title}</strong><p>{t.description||'Sem descrição.'}</p></div><div className="task-meta"><span>{t.priority}</span><span>{t.status}</span><button className="ghost" onClick={()=>editTask(t)}>Editar</button><button className="danger" onClick={()=>removeTask(t.id)}>Excluir</button></div></article>)}</div>}</section></main>
}
export default App;
