import {useEffect,useState} from 'react';

const API='http://localhost:8081/api';
const emptyProject={name:'',description:'',status:'PLANNED'};
const emptyTask={title:'',description:'',status:'TODO',priority:'MEDIUM',dueDate:'',projectId:''};

function App(){
 const [projects,setProjects]=useState([]),[tasks,setTasks]=useState([]),[stats,setStats]=useState(null);
 const [project,setProject]=useState(emptyProject),[task,setTask]=useState(emptyTask);
 const [editing,setEditing]=useState(null),[editingTask,setEditingTask]=useState(null),[error,setError]=useState('');
 const load=async()=>{try{const [p,t,d]=await Promise.all([fetch(API+'/projects'),fetch(API+'/tasks'),fetch(API+'/dashboard')]);if(!p.ok||!t.ok||!d.ok)throw new Error('Não foi possível carregar os dados.');setProjects(await p.json());setTasks(await t.json());setStats(await d.json());setError('')}catch(e){setError(e.message)}};
 useEffect(()=>{load()},[]);
 const saveProject=async e=>{e.preventDefault();const r=await fetch(editing?API+'/projects/'+editing:API+'/projects',{method:editing?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(project)});if(!r.ok){setError('Não foi possível salvar o projeto.');return}setProject(emptyProject);setEditing(null);load()};
 const removeProject=async id=>{if(!confirm('Excluir este projeto e suas tarefas?'))return;await fetch(API+'/projects/'+id,{method:'DELETE'});load()};
 const saveTask=async e=>{e.preventDefault();const r=await fetch(editingTask?API+'/tasks/'+editingTask:API+'/tasks',{method:editingTask?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...task,projectId:Number(task.projectId)})});if(!r.ok){setError('Não foi possível salvar a tarefa.');return}setTask(emptyTask);setEditingTask(null);load()};
 const removeTask=async id=>{await fetch(API+'/tasks/'+id,{method:'DELETE'});load()};
 const editProject=p=>{setEditing(p.id);setProject({name:p.name,description:p.description||'',status:p.status})};
 const editTask=t=>{setEditingTask(t.id);setTask({title:t.title,description:t.description||'',status:t.status,priority:t.priority,dueDate:t.dueDate||'',projectId:t.projectId})};
 return <main><header><div><span className="eyebrow">DEVELOPER WORKSPACE</span><h1>DevVault</h1><p>Gerencie seus projetos e tarefas em um só lugar.</p></div><button className="ghost" onClick={load}>Atualizar</button></header>
 {error&&<div className="alert">{error}</div>}
 <section className="stats">{[['Projetos',stats?.totalProjects??0],['Em andamento',stats?.inProgressProjects??0],['Concluídos',stats?.completedProjects??0],['Tarefas',stats?.totalTasks??0]].map(([l,v])=><article className="stat" key={l}><span>{l}</span><strong>{v}</strong></article>)}</section>
 <section className="grid"><div className="panel"><div className="panel-title"><h2>{editing?'Editar projeto':'Novo projeto'}</h2></div><form onSubmit={saveProject}><input required placeholder="Nome do projeto" value={project.name} onChange={e=>setProject({...project,name:e.target.value})}/><textarea placeholder="Descrição" value={project.description} onChange={e=>setProject({...project,description:e.target.value})}/><select value={project.status} onChange={e=>setProject({...project,status:e.target.value})}><option value="PLANNED">Planejado</option><option value="IN_PROGRESS">Em andamento</option><option value="COMPLETED">Concluído</option></select><button>{editing?'Salvar alterações':'Criar projeto'}</button>{editing&&<button type="button" className="ghost" onClick={()=>{setEditing(null);setProject(emptyProject)}}>Cancelar</button>}</form></div>
 <div className="panel"><div className="panel-title"><h2>{editingTask?'Editar tarefa':'Nova tarefa'}</h2></div><form onSubmit={saveTask}><input required placeholder="Título da tarefa" value={task.title} onChange={e=>setTask({...task,title:e.target.value})}/><textarea placeholder="Descrição" value={task.description} onChange={e=>setTask({...task,description:e.target.value})}/><div className="row"><select value={task.projectId} required onChange={e=>setTask({...task,projectId:e.target.value})}><option value="">Projeto</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><select value={task.priority} onChange={e=>setTask({...task,priority:e.target.value})}><option value="LOW">Baixa</option><option value="MEDIUM">Média</option><option value="HIGH">Alta</option></select></div><div className="row"><select value={task.status} onChange={e=>setTask({...task,status:e.target.value})}><option value="TODO">A fazer</option><option value="IN_PROGRESS">Em andamento</option><option value="DONE">Concluída</option></select><input type="date" value={task.dueDate} onChange={e=>setTask({...task,dueDate:e.target.value})}/></div><button>{editingTask?'Salvar tarefa':'Criar tarefa'}</button>{editingTask&&<button type="button" className="ghost" onClick={()=>{setEditingTask(null);setTask(emptyTask)}}>Cancelar</button>}</form></div></section>
 <section className="panel"><div className="panel-title"><h2>Projetos</h2><span>{projects.length} cadastrados</span></div>{projects.length===0?<div className="empty">Nenhum projeto cadastrado ainda.</div>:<div className="cards">{projects.map(p=><article className="card" key={p.id}><div className="card-top"><h3>{p.name}</h3><span className="badge">{p.status.replace('_',' ')}</span></div><p>{p.description||'Sem descrição.'}</p><small>{p.taskCount} tarefa(s)</small><div className="actions"><button className="ghost" onClick={()=>editProject(p)}>Editar</button><button className="danger" onClick={()=>removeProject(p.id)}>Excluir</button></div></article>)}</div>}</section>
 <section className="panel"><div className="panel-title"><h2>Tarefas</h2><span>{tasks.length} cadastradas</span></div>{tasks.length===0?<div className="empty">Nenhuma tarefa cadastrada ainda.</div>:<div className="task-list">{tasks.map(t=><article className="task" key={t.id}><div><strong>{t.title}</strong><p>{t.description||'Sem descrição.'}</p></div><div className="task-meta"><span>{t.priority}</span><span>{t.status}</span><button className="ghost" onClick={()=>editTask(t)}>Editar</button><button className="danger" onClick={()=>removeTask(t.id)}>Excluir</button></div></article>)}</div>}</section></main>
}
export default App;
