spring.application.name=devvault
spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jackson.serialization.write-dates-as-timestamps=false
server.port=${PORT:8081}
server.address=0.0.0.0
app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:5173}